name: 'action-fpm'
description: 'Build packages for multiple platforms using github.com/jordansissel/fpm'
branding:
  icon: 'package'  
  color: 'green'
inputs:
  fpm_opts:
    description: 'Options passed to the fpm cli tool'
    required: false
  fpm_args:
    description: 'Arguments passed to the fpm cli tool'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.fpm_args }}
